name: basic_initiative_tracker
description: Basic initiative tracker for roleplaying games.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets: 
    - assets/

msix_config:
  display_name: Basic Initiative Tracker
  publisher_display_name: Bailie Gowing
  identity_name: bailiegowing.basicInitiativeTracker
  logo_path: assets/appIcon.png
  certificate_path: C:\dev\init_tracker\Basic-Initiative-Tracker\basicInitTrackerCert.pfx
  msix_version: 1.0.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/appIcon.png"
    icon_size: 150 # min:48, max:256, default: 48


